=== xframium/xframium-java/framework/src/org/xframium/page/keyWord/provider/xsd/testRegistry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://xframium.org/xsl/xs3p.xsl"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.xframium.org/testRegistry" xmlns:tns="http://www.xframium.org/testRegistry" elementFormDefault="qualified">
  <annotation>
    <documentation xml:lang="en">
      xFramium Test Registry Definition
    </documentation>
  </annotation>

  <element name="suite" type="tns:RegistryRoot" />

  <complexType name="RegistryRoot">
    <sequence>
      <element name="import" type="tns:Import" minOccurs="0" maxOccurs="unbounded" />
      <element name="model" type="tns:Model" minOccurs="0" maxOccurs="1" />
      <element name="test" type="tns:Test" minOccurs="0" maxOccurs="unbounded" />
      <element name="function" type="tns:Test" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="Import">
    <attribute name="fileName" type="string" use="required" />
    <attribute name="includeTests" type="boolean" use="optional" default="true" />
    <attribute name="includeFunctions" type="boolean" use="optional" default="true" />
  </complexType>

  <complexType name="Model">
    <sequence>
      <element name="page" type="tns:Page" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="Page">
    <attribute name="name" type="string" use="required" />
    <attribute name="class" type="string" use="optional" />
  </complexType>

  <complexType name="Test">

    <sequence>
      <element name="description" type="tns:Description" minOccurs="0" maxOccurs="1" />
      <element name="step" type="tns:Step" minOccurs="1" maxOccurs="unbounded" />
    </sequence>

    <attribute name="name" type="string" use="required" />
    <attribute name="dataDriver" type="string" use="optional" />
    <attribute name="dataProvider" type="string" use="optional" />
    <attribute name="tagNames" type="string" use="optional" />
    <attribute name="linkId" type="string" use="optional" />
    <attribute name="timed" type="boolean" use="optional" default="false" />
    <attribute name="threshold" type="integer" use="optional" default="0" />
    <attribute name="active" type="boolean" use="optional" default="true" />
    <attribute name="os" type="string" use="optional" />
    <attribute name="contentKeys" type="string" use="optional" />

  </complexType>

  <complexType name="Description">
    <simpleContent>
      <extension base="string" />
    </simpleContent>
  </complexType>

  <complexType name="Step">
    <sequence>
      <element name="parameter" type="tns:Parameter" minOccurs="0" maxOccurs="unbounded" />
      <element name="token" type="tns:Token" minOccurs="0" maxOccurs="unbounded" />
      <element name="step" type="tns:Step" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="name" type="string" use="required" />
    <attribute name="page" type="string" use="optional" />
    <attribute name="type" use="required">
      <simpleType>
        <restriction base="string">
          <enumeration value="CALL" />
          <enumeration value="CLICK" />
          <enumeration value="EXISTS" />
          <enumeration value="FUNCTION" />
          <enumeration value="GESTURE" />
          <enumeration value="RETURN" />
          <enumeration value="SET" />
          <enumeration value="VALUE" />
          <enumeration value="GET" />
          <enumeration value="WAIT" />
          <enumeration value="WAIT_FOR" />
          <enumeration value="ATTRIBUTE" />
          <enumeration value="LOOP" />
          <enumeration value="BREAK" />
          <enumeration value="DEVICE" />
          <enumeration value="FORK" />
          <enumeration value="VISIBLE" />
          <enumeration value="VERIFY_COLOR" />
          <enumeration value="VERIFY_CONTRAST" />
          <enumeration value="WINDOW" />
          <enumeration value="EXECJS" />
          <enumeration value="EXECWS" />
          <enumeration value="COMPARE" />
          <enumeration value="STRING" />
          <enumeration value="MATH" />
          <enumeration value="MOUSE" />
          <enumeration value="CACHE" />
          <enumeration value="REPORT" />
          <enumeration value="SYNC" />
          <enumeration value="OPEN_PAGE" />
          <enumeration value="ADD_COOKIE" />
          <enumeration value="DELETE_COOKIE" />
          <enumeration value="DELETE_COOKIES" />
          <enumeration value="GET_COOKIE" />
          <enumeration value="GET_COOKIES" />
          <enumeration value="ADD_DEVICE" />
          <enumeration value="AT" />
          <enumeration value="HAS_FOCUS" />
          <enumeration value="ALIGN" />
          <enumeration value="PERFECTO_SCRIPT" />
          <enumeration value="ELSE" />
          <enumeration value="STATE" />
          <enumeration value="ALERT" />
          <enumeration value="SQL" />
          <enumeration value="OPERATOR" />
          <enumeration value="NAVIGATE" />
          <enumeration value="VISUAL" />
          <enumeration value="SET_CONTENT_KEY" />
          <enumeration value="BROWSER" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="active" type="boolean" use="optional" default="true" />
    <attribute name="linkId" type="string" use="optional" />
    <attribute name="os" type="string" use="optional" />
    <attribute name="poi" type="string" use="optional" />
    <attribute name="threshold" type="integer" use="optional" default="0" />
    <attribute name="timed" type="boolean" use="optional" default="false" />
    <attribute name="inverse" type="boolean" use="optional" default="false" />
    <attribute name="startAt" type="boolean" use="optional" default="false" />
    <attribute name="breakpoint" type="boolean" use="optional" default="false" />
    <attribute name="wait" type="integer" use="optional" default="0" />
    <attribute name="failureMode" use="optional" default="ERROR">
      <simpleType>
        <restriction base="string">
          <enumeration value="ERROR" />
          <enumeration value="IGNORE" />
          <enumeration value="LOG_IGNORE" />
        </restriction>
      </simpleType>
    </attribute>

    <attribute name="validation" type="string" use="optional" />
    <attribute name="validationType" use="optional">
      <simpleType>
        <restriction base="string">
          <enumeration value="REGEX" />
          <enumeration value="EMPTY" />
          <enumeration value="NOT_EMPTY" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="context" type="string" use="optional" />
    <attribute name="device" type="string" use="optional" />
    <attribute name="tagNames" type="string" use="optional" />

  </complexType>

  <complexType name="Token">
    <attribute name="type" use="optional">
      <simpleType>
        <restriction base="string">
          <enumeration value="CONTEXT" />
          <enumeration value="PROPERTY" />
          <enumeration value="STATIC" />
          <enumeration value="CONTENT" />
          <enumeration value="DATA" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="value" type="string" use="required" />
    <attribute name="name" type="string" use="required" />
  </complexType>

  <complexType name="Parameter">
    <sequence>
      <element name="token" type="tns:Token" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="type" use="optional">
      <simpleType>
        <restriction base="string">
          <enumeration value="CONTEXT" />
          <enumeration value="PROPERTY" />
          <enumeration value="STATIC" />
          <enumeration value="CONTENT" />
          <enumeration value="DATA" />
          <enumeration value="FILE" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="value" type="string" use="required" />
    <attribute name="name" type="string" use="optional" />
    <attribute name="usage" type="string" use="optional" />
  </complexType>



</schema>

=== xframium/xframium-java/testing/general/kw-get.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>

  <function name="kw-get" active="true">
    
    <step type="GET" name="colorContrastAA" page="home" context="getValue" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="Double AA" />
      <parameter type="CONTEXT" value="getValue" />
    </step>
    
    <step type="GET" name="colorContrastAA" page="home" >
      <parameter type="STATIC" value="Double AA" />
    </step>

  </function>

</suite>

=== xframium/xframium-java/testing/general/kw-visible.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>

  <function name="kw-visible" active="true">
    
    <step type="EXISTS" name="aOpen" page="home"  />
    <step type="EXISTS" name="deleteButton" page="home"  />
    
    <step type="VISIBLE" name="deleteButton" page="home" inverse="true" />
    <step type="CLICK" name="aOpen" page="home" wait="1000" />
    <step type="VISIBLE" name="deleteButton" page="home" />
    <step type="CLICK" name="aOpen" page="home" wait="1000" />
    <step type="VISIBLE" name="deleteButton" page="home" inverse="true" />


  </function>

</suite>

=== xframium/xframium-java/testing/general/kw-exists.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>




  <function name="kw-exists" active="true">
    
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
    
    
    <step type="EXISTS" name="elementList" page="home" context="existsList" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="3" />
      <parameter type="CONTEXT" value="existsList_count" />
    </step>
    

  </function>

</suite>

=== xframium/xframium-java/testing/general/kw-string.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>




  <function name="kw-string" active="true">
    
    <step type="STRING" name="colorCheck" page="home" context="trimmedValue">
      <parameter type="STATIC" value="trim" />
    </step>
    
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="Test Color" />
      <parameter type="CONTEXT" value="trimmedValue" />
    </step>
    
    <step type="STRING" name="colorCheck" page="home" context="upperValue">
      <parameter type="CONTEXT" value="trimmedValue" />
      <parameter type="STATIC" value="upper" />
    </step>
    
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="TEST COLOR" />
      <parameter type="CONTEXT" value="upperValue" />
    </step>
    
    <step type="STRING" name="colorCheck" page="home" context="lowerValue">
      <parameter type="CONTEXT" value="upperValue" />
      <parameter type="STATIC" value="lower" />
    </step>
    
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="test color" />
      <parameter type="CONTEXT" value="lowerValue" />
    </step>
    
    <step type="STRING" name="colorCheck" page="home" context="decimalValue">
      <parameter type="STATIC" value="123.9999999" />
      <parameter type="STATIC" value="decimal" />
      <parameter type="STATIC" value="#.##" />
    </step>
    
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="123.99" />
      <parameter type="CONTEXT" value="decimalValue" />
    </step>
    
    <step type="STRING" name="colorCheck" page="home" context="lowerValue">
      <parameter type="STATIC" value="lower" />
      <parameter type="CONTEXT" value="contains" />
      <parameter type="STATIC" value="my lower back" />
    </step>


  </function>

</suite>

=== xframium/xframium-java/testing/functions/xTest/kw-attribute.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <function name="kw-attribute" inputPage="xTest.home" outputPage="xTest.home" active="true">
    <description></description>
    <step name="toggleButton" site="xTest" page="home" type="ATTRIBUTE" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR">
      <parameter type="STATIC" value="button" />
      <parameter type="STATIC" value="type" />
    </step>
    
    <step name="toggleButton" site="xTest" page="home" type="ATTRIBUTE" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR" context="targetClass">
      <parameter type="STATIC" value="class" />
    </step>
    
    <step name="toggleButton" site="xTest" page="home" type="ATTRIBUTE" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR" context="targetToggle">
      <parameter type="STATIC" value="data-toggle" />
    </step>
    
    <step name="toggleButton" site="xTest" page="home" type="REPORT" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR">
      <parameter type="CONTEXT" value="targetClass" />
      <parameter type="CONTEXT" value="targetToggle" />
    </step>
    
    <step name="attributeCompare" site="xTest" page="home" type="COMPARE" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR">
      <parameter type="STATIC" value="button" />
      <parameter type="CONTEXT" value="attributeValue" />
    </step>
    <step name="toggleButton" site="xTest" page="home" type="ATTRIBUTE" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR">
      <parameter type="STATIC" value="none" />
      <parameter type="STATIC" value="STYLE.text-align" />
    </step>
    <step name="toggleButton" site="xTest" page="home" type="ATTRIBUTE" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR" context="attributeStyleValue">
      <parameter type="STATIC" value="STYLE.background-image" />
    </step>
    <step name="attributeCompare" site="xTest" page="home" type="COMPARE" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR">
      <parameter type="STATIC" value="none" />
      <parameter type="CONTEXT" value="attributeStyleValue" />
    </step>
  </function>
</suite>

=== xframium/xframium-java/testing/general/kw-loop.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>




  <function name="kw-loop" active="true">
    
    <step type="LOOP" name="data based loop" page="home" >
      <parameter type="STATIC" value="data{dataLoop}"/>
      <parameter type="STATIC" value="setValue"/>
    </step>
    
    <step type="ATTRIBUTE" name="focusId" page="home" >
      <parameter type="STATIC" value="three" />
      <parameter type="STATIC" value="value" />
    </step>
    
    <step type="SET" name="focusId" page="home" >
      <parameter type="STATIC" value="" />
    </step>

    <step type="LOOP" name="data based loop with break" page="home" >
      <parameter type="STATIC" value="data{dataLoop}"/>
      <parameter type="STATIC" value="setValueWithBreak"/>
    </step>
    
    <step type="ATTRIBUTE" name="focusId" page="home" >
      <parameter type="STATIC" value="two" />
      <parameter type="STATIC" value="value" />
    </step>
    
    <step type="SET" name="focusId" page="home" >
      <parameter type="STATIC" value="" />
    </step>
    
    <step type="LOOP" name="element list based loop" page="home" >
      <parameter type="STATIC" value="elementList"/>
      <parameter type="STATIC" value="setValueFromElement"/>
    </step>
    
    <step type="ATTRIBUTE" name="focusId" page="home" >
      <parameter type="STATIC" value="Value Three" />
      <parameter type="STATIC" value="value" />
    </step>
    
    <step type="SET" name="focusId" page="home" >
      <parameter type="STATIC" value="" />
    </step>
    
    <step type="LOOP" name="numerical based loop" page="home" >
      <parameter type="STATIC" value="3"/>
      <parameter type="STATIC" value="setValueFromNumericIndex"/>
    </step>
    
    <step type="ATTRIBUTE" name="focusId" page="home" >
      <parameter type="STATIC" value="3" />
      <parameter type="STATIC" value="value" />
    </step>
    
    <step type="SET" name="focusId" page="home" >
      <parameter type="STATIC" value="" />
    </step>
    
    

  </function>
  
  <function name="setValueFromNumericIndex" active="true">
    <step type="SET" name="focusId" page="home" >
      <parameter type="CONTEXT" value="_LOOP.INDEX" />
    </step>
  </function>
  
  <function name="setValueFromElement" active="true">
    <step type="GET" name="_CONTEXT.ELEMENT" page="home" context="elementValue"/>
    <step type="SET" name="focusId" page="home" >
      <parameter type="CONTEXT" value="elementValue" />
    </step>
  </function>
  
  <function name="setValue" active="true">
    <step type="SET" name="focusId" page="home" >
      <parameter type="DATA" value="dataLoop.value" />
    </step>
  </function>
  
  <function name="setValueWithBreak" active="true">
    <step type="SET" name="focusId" page="home" >
      <parameter type="DATA" value="dataLoop.value" />
    </step>
    
    <step type="COMPARE" name="isTwo" page="home" failureMode="IGNORE">
      <parameter type="DATA" value="dataLoop.value" />
      <parameter type="STATIC" value="two"/>
      <step type="BREAK" name="two was found" page="home"/>
    </step>
    
  </function>

</suite>

=== xframium/xframium-java/testing/general/kw-set.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>

  <function name="kw-set" active="true">
    
    <step type="SET" name="focusId" page="home" >
      <parameter type="STATIC" value="SET_VALUE" />
    </step>
    <step type="ATTRIBUTE" name="focusId" page="home" >
      <parameter type="STATIC" value="SET_VALUE" />
      <parameter type="STATIC" value="value" />
    </step>
    
    <step type="SET" name="focusId" page="home" >
      <parameter type="STATIC" value="NEW SET_VALUE" />
      <parameter type="STATIC" value="DEFAULT" />
    </step>
    <step type="ATTRIBUTE" name="focusId" page="home" >
      <parameter type="STATIC" value="NEW SET_VALUE" />
      <parameter type="STATIC" value="value" />
    </step>
    
    <step type="SET" name="focusId" page="home" >
      <parameter type="STATIC" value="xxx" />
      <parameter type="STATIC" value="SINGLE" />
    </step>
    <step type="ATTRIBUTE" name="focusId" page="home" >
      <parameter type="STATIC" value="NEW SET_VALUExxx" />
      <parameter type="STATIC" value="value" />
    </step>
    
    <step type="SET" name="focusId" page="home" >
      <parameter type="STATIC" value="" />
    </step>
    
    <step type="SET" name="selectBox" page="home" wait="1000">
      <parameter type="STATIC" value="2" />
    </step>
    
    <step type="SET" name="selectBox" page="home" wait="1000">
      <parameter type="STATIC" value="Three" />
    </step>
    


  </function>

</suite>

=== xframium/xframium-java/testing/general/kw-operator.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>




  <function name="kw-operator" active="true">
    <step type="LOOP" name="data based loop" page="home" >
      <parameter type="STATIC" value="data{dataLoop}"/>
      <parameter type="STATIC" value="orSet"/>
    </step>
    
    <step type="ATTRIBUTE" name="focusId" page="home" >
      <parameter type="STATIC" value="OR" />
      <parameter type="STATIC" value="value" />
    </step>
    
    <step type="LOOP" name="data based loop" page="home" >
      <parameter type="STATIC" value="data{dataLoop}"/>
      <parameter type="STATIC" value="andSet"/>
    </step>
    
    <step type="ATTRIBUTE" name="focusId" page="home" >
      <parameter type="STATIC" value="OR" />
      <parameter type="STATIC" value="value" />
    </step>
    
    <step type="SET" name="focusId" page="home" >
      <parameter type="STATIC" value="" />
    </step>

  </function>
  
  <function name="orSet" active="true">
    <step type="OPERATOR" name="one or three" page="home" failureMode="IGNORE">
      <parameter type="STATIC" value="OR" />
      <parameter type="DATA" value="dataLoop.value" />
      <parameter type="STATIC" value="one" />
      <parameter type="DATA" value="dataLoop.value" />
      <parameter type="STATIC" value="two" />
      <step type="SET" name="focusId" page="home" >
        <parameter type="STATIC" value="OR" />
      </step>
    </step>
  </function>
  
  <function name="andSet" active="true">
    <step type="OPERATOR" name="one or three" page="home" failureMode="IGNORE" >
      <parameter type="STATIC" value="AND" />
      <parameter type="DATA" value="dataLoop.value" />
      <parameter type="STATIC" value="one" />
      <parameter type="DATA" value="dataLoop.value" />
      <parameter type="STATIC" value="two" />
      <step type="SET" name="focusId" page="home" >
        <parameter type="STATIC" value="AND" />
      </step>
    </step>
  </function>

</suite>
