=== xframium/xframium-java/framework/src/org/xframium/page/keyWord/provider/xsd/testRegistry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://xframium.org/xsl/xs3p.xsl"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.xframium.org/testRegistry" xmlns:tns="http://www.xframium.org/testRegistry" elementFormDefault="qualified">
  <annotation>
    <documentation xml:lang="en">
      xFramium Test Registry Definition
    </documentation>
  </annotation>

  <element name="suite" type="tns:RegistryRoot" />

  <complexType name="RegistryRoot">
    <sequence>
      <element name="import" type="tns:Import" minOccurs="0" maxOccurs="unbounded" />
      <element name="model" type="tns:Model" minOccurs="0" maxOccurs="1" />
      <element name="test" type="tns:Test" minOccurs="0" maxOccurs="unbounded" />
      <element name="function" type="tns:Test" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="Import">
    <attribute name="fileName" type="string" use="required" />
    <attribute name="includeTests" type="boolean" use="optional" default="true" />
    <attribute name="includeFunctions" type="boolean" use="optional" default="true" />
  </complexType>

  <complexType name="Model">
    <sequence>
      <element name="page" type="tns:Page" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="Page">
    <attribute name="name" type="string" use="required" />
    <attribute name="class" type="string" use="optional" />
  </complexType>

  <complexType name="Test">

    <sequence>
      <element name="description" type="tns:Description" minOccurs="0" maxOccurs="1" />
      <element name="step" type="tns:Step" minOccurs="1" maxOccurs="unbounded" />
    </sequence>

    <attribute name="name" type="string" use="required" />
    <attribute name="dataDriver" type="string" use="optional" />
    <attribute name="dataProvider" type="string" use="optional" />
    <attribute name="tagNames" type="string" use="optional" />
    <attribute name="linkId" type="string" use="optional" />
    <attribute name="timed" type="boolean" use="optional" default="false" />
    <attribute name="threshold" type="integer" use="optional" default="0" />
    <attribute name="active" type="boolean" use="optional" default="true" />
    <attribute name="os" type="string" use="optional" />
    <attribute name="contentKeys" type="string" use="optional" />

  </complexType>

  <complexType name="Description">
    <simpleContent>
      <extension base="string" />
    </simpleContent>
  </complexType>

  <complexType name="Step">
    <sequence>
      <element name="parameter" type="tns:Parameter" minOccurs="0" maxOccurs="unbounded" />
      <element name="token" type="tns:Token" minOccurs="0" maxOccurs="unbounded" />
      <element name="step" type="tns:Step" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="name" type="string" use="required" />
    <attribute name="page" type="string" use="optional" />
    <attribute name="type" use="required">
      <simpleType>
        <restriction base="string">
          <enumeration value="CALL" />
          <enumeration value="CLICK" />
          <enumeration value="EXISTS" />
          <enumeration value="FUNCTION" />
          <enumeration value="GESTURE" />
          <enumeration value="RETURN" />
          <enumeration value="SET" />
          <enumeration value="VALUE" />
          <enumeration value="GET" />
          <enumeration value="WAIT" />
          <enumeration value="WAIT_FOR" />
          <enumeration value="ATTRIBUTE" />
          <enumeration value="LOOP" />
          <enumeration value="BREAK" />
          <enumeration value="DEVICE" />
          <enumeration value="FORK" />
          <enumeration value="VISIBLE" />
          <enumeration value="VERIFY_COLOR" />
          <enumeration value="VERIFY_CONTRAST" />
          <enumeration value="WINDOW" />
          <enumeration value="EXECJS" />
          <enumeration value="EXECWS" />
          <enumeration value="COMPARE" />
          <enumeration value="STRING" />
          <enumeration value="MATH" />
          <enumeration value="MOUSE" />
          <enumeration value="CACHE" />
          <enumeration value="REPORT" />
          <enumeration value="SYNC" />
          <enumeration value="OPEN_PAGE" />
          <enumeration value="ADD_COOKIE" />
          <enumeration value="DELETE_COOKIE" />
          <enumeration value="DELETE_COOKIES" />
          <enumeration value="GET_COOKIE" />
          <enumeration value="GET_COOKIES" />
          <enumeration value="ADD_DEVICE" />
          <enumeration value="AT" />
          <enumeration value="HAS_FOCUS" />
          <enumeration value="ALIGN" />
          <enumeration value="PERFECTO_SCRIPT" />
          <enumeration value="ELSE" />
          <enumeration value="STATE" />
          <enumeration value="ALERT" />
          <enumeration value="SQL" />
          <enumeration value="OPERATOR" />
          <enumeration value="NAVIGATE" />
          <enumeration value="VISUAL" />
          <enumeration value="SET_CONTENT_KEY" />
          <enumeration value="BROWSER" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="active" type="boolean" use="optional" default="true" />
    <attribute name="linkId" type="string" use="optional" />
    <attribute name="os" type="string" use="optional" />
    <attribute name="poi" type="string" use="optional" />
    <attribute name="threshold" type="integer" use="optional" default="0" />
    <attribute name="timed" type="boolean" use="optional" default="false" />
    <attribute name="inverse" type="boolean" use="optional" default="false" />
    <attribute name="startAt" type="boolean" use="optional" default="false" />
    <attribute name="breakpoint" type="boolean" use="optional" default="false" />
    <attribute name="wait" type="integer" use="optional" default="0" />
    <attribute name="failureMode" use="optional" default="ERROR">
      <simpleType>
        <restriction base="string">
          <enumeration value="ERROR" />
          <enumeration value="IGNORE" />
          <enumeration value="LOG_IGNORE" />
        </restriction>
      </simpleType>
    </attribute>

    <attribute name="validation" type="string" use="optional" />
    <attribute name="validationType" use="optional">
      <simpleType>
        <restriction base="string">
          <enumeration value="REGEX" />
          <enumeration value="EMPTY" />
          <enumeration value="NOT_EMPTY" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="context" type="string" use="optional" />
    <attribute name="device" type="string" use="optional" />
    <attribute name="tagNames" type="string" use="optional" />

  </complexType>

  <complexType name="Token">
    <attribute name="type" use="optional">
      <simpleType>
        <restriction base="string">
          <enumeration value="CONTEXT" />
          <enumeration value="PROPERTY" />
          <enumeration value="STATIC" />
          <enumeration value="CONTENT" />
          <enumeration value="DATA" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="value" type="string" use="required" />
    <attribute name="name" type="string" use="required" />
  </complexType>

  <complexType name="Parameter">
    <sequence>
      <element name="token" type="tns:Token" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="type" use="optional">
      <simpleType>
        <restriction base="string">
          <enumeration value="CONTEXT" />
          <enumeration value="PROPERTY" />
          <enumeration value="STATIC" />
          <enumeration value="CONTENT" />
          <enumeration value="DATA" />
          <enumeration value="FILE" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="value" type="string" use="required" />
    <attribute name="name" type="string" use="optional" />
    <attribute name="usage" type="string" use="optional" />
  </complexType>



</schema>

=== xframium/xframium-java/testing/general/kw-focus.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>




  <function name="kw-focus" active="true">
    
    <step type="CLICK" name="toggleButton" page="home" wait="500"/>
    <step type="CLICK" name="toggleButton" page="home"/>
    
    <step type="HAS_FOCUS" name="focusId" page="home" inverse="true" />
    <step type="CLICK" name="focusId" page="home"/>
    <step type="WAIT" name="focusId" page="home"/>
    <step type="HAS_FOCUS" name="focusId" page="home" />
   
  </function>

</suite>

=== xframium/xframium-java/testing/general/kw-attribute.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>

  <function name="kw-attribute" active="true">
    
    <step type="ATTRIBUTE" name="toggleButton" page="home" >
      <parameter type="STATIC" value="button" />
      <parameter type="STATIC" value="type" />
    </step>
    
    <step type="ATTRIBUTE" name="toggleButton" page="home" context="attributeValue">
      <parameter type="STATIC" value="type" />
    </step>
    
    <step type="COMPARE" name="attributeCompare" page="home">
      <parameter type="STATIC" value="button" />
      <parameter type="CONTEXT" value="attributeValue" />
    </step>
    
    <step type="ATTRIBUTE" name="toggleButton" page="home" >
      <parameter type="STATIC" value="rgba(38, 90, 136, 1)" />
      <parameter type="STATIC" value="STYLE.background-color" />
    </step>
    
    <step type="ATTRIBUTE" name="toggleButton" page="home" context="attributeStyleValue">
      <parameter type="STATIC" value="STYLE.background-color" />
    </step>
    
    <step type="COMPARE" name="attributeCompare" page="home">
      <parameter type="STATIC" value="rgba(38, 90, 136, 1)" />
      <parameter type="CONTEXT" value="attributeStyleValue" />
    </step>
    

  </function>

</suite>

=== xframium/xframium-java/testing/general/kw-navigate.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />
    <page name="page two" />

  </model>




  <function name="kw-navigate" active="true">
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
    
    <step type="CLICK" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="0" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>

    <step type="NAVIGATE" name="refresh screen" page="home" >
      <parameter type="STATIC" value="REFRESH" />
    </step>
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
    
    <step type="CLICK" name="testingTwo" page="home" />
    <step type="EXISTS" name="screenTwo" page="page two" />
    
    <step type="NAVIGATE" name="refresh screen" page="home" >
      <parameter type="STATIC" value="BACK" />
    </step>
    <step type="EXISTS" name="testingTwo" page="home" />
    <step type="NAVIGATE" name="refresh screen" page="home" >
      <parameter type="STATIC" value="FORWARD" />
    </step>
    <step type="EXISTS" name="screenTwo" page="page two" />
    <step type="NAVIGATE" name="refresh screen" page="home" >
      <parameter type="STATIC" value="BACK" />
    </step>
    <step type="NAVIGATE" name="refresh screen" page="home" >
      <parameter type="STATIC" value="REFRESH" />
    </step>
  </function>

</suite>

=== xframium/xframium-java/testing/general/kw-execjs.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>

  <function name="kw-execjs" active="true">
    
    <step type="EXECJS" name="js" page="home" >
      <parameter type="STATIC" value="alert( 'EXECJS Alert Message' )" />
    </step>
    <step type="ALERT" name="ACCEPT" page="home" context="alertValue" />
    
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="EXECJS Alert Message" />
      <parameter type="CONTEXT" value="alertValue" />
    </step>
    
    

  </function>

</suite>

=== xframium/xframium-java/testing/tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <import fileName="general/kw-exists.xml" />
  <import fileName="general/kw-alert.xml" />
  <import fileName="general/kw-align.xml" />
  <import fileName="general/kw-attribute.xml" />
  <import fileName="general/kw-cache.xml" />
  <import fileName="general/kw-call.xml" />
  <import fileName="general/kw-compare.xml" />
  <import fileName="general/kw-checkcolor.xml" />
  <import fileName="general/kw-click.xml" />
  <import fileName="general/kw-checkcontrast.xml" />
  <import fileName="general/kw-dumpstate.xml" />
  <import fileName="general/kw-else.xml" />
  <import fileName="general/kw-execjs.xml" />
  <import fileName="general/kw-focus.xml" />
  <import fileName="general/kw-loop.xml" />
  <import fileName="general/kw-math.xml" />
  <import fileName="general/kw-mouse.xml" />
  <import fileName="general/kw-navigate.xml" />
  <import fileName="general/kw-operator.xml" />
  <import fileName="general/kw-report.xml" />
  <import fileName="general/kw-set.xml" />
  <import fileName="general/kw-string.xml" />
  <import fileName="general/kw-get.xml" />
  <import fileName="general/kw-visible.xml" />
  <import fileName="general/kw-wait.xml" />
  <import fileName="general/kw-waitfor.xml" />
  <import fileName="general/kw-window.xml" />
  <import fileName="general/kw-browser.xml" />
  <import fileName="general/kw-execws.xml" />
  <model>
    <page name="home" />
  </model>
  <test name="xFramium General KeyWord Test" active="true" dataProvider="callTest">
    <description>Tests the general keywords that apply to both Web and Native applications across web and mobile devices</description>
    <step type="CALL" name="kw-exists" page="home" />
    <step type="CALL" name="kw-alert" page="home" os="Windows,MACOS" active="true" />
    <step type="CALL" name="kw-align" page="home" />
    <step type="CALL" name="kw-attribute" page="home" />
    <step type="CALL" name="kw-cache" page="home" />
    <step type="CALL" name="kw-call" page="home" />
    <step type="CALL" name="kw-checkcolor" page="home" os="Windows,MACOS" />
    <step type="CALL" name="kw-click" page="home" />
    <step type="CALL" name="kw-compare" page="home" />
    <step type="CALL" name="kw-checkcontrast" page="home" os="Windows,MACOS" />
    <step type="CALL" name="kw-dumpstate" page="home" />
    <step type="CALL" name="kw-else" page="home" />
    <step type="CALL" name="kw-execjs" page="home" os="Windows,MACOS" />
    <step type="CALL" name="kw-focus" page="home" active="false" />
    <step type="CALL" name="kw-loop" page="home" />
    <step type="CALL" name="kw-mouse" page="home" os="Windows,MACOS" />
    <step type="CALL" name="kw-navigate" page="home" />
    <step type="CALL" name="kw-operator" page="home" />
    <step type="CALL" name="kw-report" page="home" />
    <step type="CALL" name="kw-set" page="home" />
    <step type="CALL" name="kw-string" page="home" />
    <step type="CALL" name="kw-get" page="home" />
    <step type="CALL" name="kw-visible" page="home" />
    <step type="CALL" name="kw-wait" page="home" />
    <step type="CALL" name="kw-waitfor" page="home" />
    <step type="CALL" name="kw-window" page="home" />
    <step type="CALL" name="kw-browser" page="home" />
    <step type="CALL" name="kw-execws" page="home" />
  </test>

  <test name="xFramium REGEX" active="true">
    <description>Tests that the specified step is ignored for a specific OS type</description>
    <step type="EXISTS" name="focusId" page="home" />
    <step type="SET" name="focusId" page="home" >
        <parameter type="STATIC" value="100.23" />
    </step>
    <step type="GET" name="focusId" page="home" validation="^-?(?:0|[1-9]\d{0,2}(?:,?\d{3})*)(?:\.\d+)?$" validationType="REGEX" context="currency" />
    
    <step type="SET" name="focusId" page="home" >
        <parameter type="STATIC" value="2,123.23" />
    </step>
    <step type="GET" name="focusId" page="home" validation="^-?(?:0|[1-9]\d{0,2}(?:,?\d{3})*)(?:\.\d+)?$" validationType="REGEX" context="currency2" />
    
    <step type="SET" name="focusId" page="home" >
        <parameter type="STATIC" value="100" />
    </step>
    <step type="GET" name="focusId" page="home" validation="^-?(?:0|[1-9]\d{0,2}(?:,?\d{3})*)(?:\.\d+)?$" validationType="REGEX" context="currency3" />
    
    <step type="SET" name="focusId" page="home"  >
        <parameter type="STATIC" value="100.010A" />
    </step>
    <step type="GET" name="focusId" page="home" validation="^-?(?:0|[1-9]\d{0,2}(?:,?\d{3})*)(?:\.\d+)?$" validationType="REGEX" context="currency4" inverse="true" />
  </test>
  
  <test name="xFramium OS Step Filter" active="true" dataProvider="callTest" os="WINDOWS">
    <description>Tests that the specified step is ignored for a specific OS type</description>
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
    <step type="CLICK" name="toggleButton" page="home" os="ANDROID,IOS" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
  </test>
  <test name="xFramium Page Element Context" active="true" dataProvider="callTest" os="ANDROID,IOS">
    <description>Tests that the specified step is ignored for a specific OS type</description>
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleButtonWeb" page="home" />
    <step type="EXISTS" name="toggleButtonNative" page="home" inverse="true" />
  </test>
  <test name="xFramium OS Step Filter" active="true" dataProvider="callTest" os="WINDOWS">
    <description>Tests that the specified step is ignored for a specific OS type</description>
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
    <step type="CLICK" name="toggleButton" page="home" os="ANDROID,IOS" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
  </test>
  <test name="xFramium Dump State Test" active="true" dataProvider="callTest" os="WINDOWS">
    <description>Tests that the specified step is ignored for a specific OS type</description>
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
    <step type="STATE" name="dumpState" page="home">
      <parameter type="STATIC" value="beforeClick" />
    </step>
    <step type="CLICK" name="toggleButton" page="home" />
    <step type="STATE" name="afterState" page="home">
      <parameter type="STATIC" value="afterClick" />
    </step>
  </test>
  <test name="xFramium Dump State Historical Test" active="true" dataProvider="callTest" os="WINDOWS">
    <description>Tests that the specified step is ignored for a specific OS type</description>
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
    <step type="STATE" name="dumpState" page="home">
      <parameter type="STATIC" value="beforeClick" />
      <parameter type="STATIC" value="5" />
    </step>
    <step type="CLICK" name="toggleButton" page="home" />
    <step type="STATE" name="afterState" page="home">
      <parameter type="STATIC" value="afterClick" />
      <parameter type="STATIC" value="2" />
      <parameter type="STATIC" value="0" />
    </step>
  </test>
  <test name="xFramium device tag Step Filter" active="true" dataProvider="callTest" deviceTags="tagTest">
    <description>Tests that the specified step is ignored for a specific device tag</description>
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
    <step type="CLICK" name="toggleButton" page="home" deviceTags="badClick" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
    <step type="CLICK" name="toggleButton" page="home" deviceTags="goodClick" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="0" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
  </test>
</suite>

=== xframium/xframium-java/testing/general/kw-checkcontrast.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>

  <function name="kw-checkcontrast" active="true">

    <step type="VERIFY_CONTRAST" name="alertButton" page="home">
      <parameter type="STATIC" value="high" />
      <parameter type="STATIC" value="7" />
      <parameter type="STATIC" value="21" />
    </step>
    
    <step type="VERIFY_CONTRAST" name="colorContrastAA" page="home" inverse="true">
      <parameter type="STATIC" value="high" />
      <parameter type="STATIC" value="7" />
      <parameter type="STATIC" value="21" />
    </step>
    
    <step type="VERIFY_CONTRAST" name="colorContrastAA" page="home">
      <parameter type="STATIC" value="high" />
      <parameter type="STATIC" value="4.5" />
      <parameter type="STATIC" value="7" />
    </step>
    
    <step type="VERIFY_CONTRAST" name="colorContrast" page="home" inverse="true">
      <parameter type="STATIC" value="high" />
      <parameter type="STATIC" value="4.5" />
      <parameter type="STATIC" value="21" />
    </step>
    


  </function>

</suite>

=== xframium/xframium-java/testing/general/kw-math.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>




  <function name="kw-math" active="true">
    
    <step type="MATH" name="add" page="home" >
      <parameter type="STATIC" value="=100" />
      <parameter type="STATIC" value="75" />
      <parameter type="STATIC" value="25" />
    </step>
    
    <step type="MATH" name="subtract" page="home" >
      <parameter type="STATIC" value="=50" />
      <parameter type="STATIC" value="75" />
      <parameter type="STATIC" value="25" />
    </step>
    

  </function>

</suite>

=== xframium/xframium-java/testing/general/kw-mouse.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>




  <function name="kw-mouse" active="true">
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home" failureMode="IGNORE">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
      <step page="home" type="ELSE" name="elseCondition">
        <step type="CLICK" name="toggleButton" page="home" />
      </step>
    </step>
    
    <step type="MOUSE" name="toggleButton" page="home" >
      <parameter type="STATIC" value="MOVE_TO" />
    </step>
    <step type="MOUSE" name="toggleButton" page="home" >
      <parameter type="STATIC" value="PRESS" />
    </step>
    <step type="MOUSE" name="toggleButton" page="home" >
      <parameter type="STATIC" value="RELEASE" />
    </step>
    
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="0" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
    <step type="CLICK" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleButton" page="home" />
    <step type="EXISTS" name="toggleValue" page="home" context="existsSingle" />
    <step type="COMPARE" name="existsCompare" page="home">
      <parameter type="STATIC" value="1" />
      <parameter type="CONTEXT" value="existsSingle" />
    </step>
    

  </function>

</suite>
