=== xframium/xframium-java/framework/src/org/xframium/page/keyWord/provider/xsd/testRegistry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://xframium.org/xsl/xs3p.xsl"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.xframium.org/testRegistry" xmlns:tns="http://www.xframium.org/testRegistry" elementFormDefault="qualified">
  <annotation>
    <documentation xml:lang="en">
      xFramium Test Registry Definition
    </documentation>
  </annotation>

  <element name="suite" type="tns:RegistryRoot" />

  <complexType name="RegistryRoot">
    <sequence>
      <element name="import" type="tns:Import" minOccurs="0" maxOccurs="unbounded" />
      <element name="model" type="tns:Model" minOccurs="0" maxOccurs="1" />
      <element name="test" type="tns:Test" minOccurs="0" maxOccurs="unbounded" />
      <element name="function" type="tns:Test" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="Import">
    <attribute name="fileName" type="string" use="required" />
    <attribute name="includeTests" type="boolean" use="optional" default="true" />
    <attribute name="includeFunctions" type="boolean" use="optional" default="true" />
  </complexType>

  <complexType name="Model">
    <sequence>
      <element name="page" type="tns:Page" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="Page">
    <attribute name="name" type="string" use="required" />
    <attribute name="class" type="string" use="optional" />
  </complexType>

  <complexType name="Test">

    <sequence>
      <element name="description" type="tns:Description" minOccurs="0" maxOccurs="1" />
      <element name="step" type="tns:Step" minOccurs="1" maxOccurs="unbounded" />
    </sequence>

    <attribute name="name" type="string" use="required" />
    <attribute name="dataDriver" type="string" use="optional" />
    <attribute name="dataProvider" type="string" use="optional" />
    <attribute name="tagNames" type="string" use="optional" />
    <attribute name="linkId" type="string" use="optional" />
    <attribute name="timed" type="boolean" use="optional" default="false" />
    <attribute name="threshold" type="integer" use="optional" default="0" />
    <attribute name="active" type="boolean" use="optional" default="true" />
    <attribute name="os" type="string" use="optional" />
    <attribute name="contentKeys" type="string" use="optional" />

  </complexType>

  <complexType name="Description">
    <simpleContent>
      <extension base="string" />
    </simpleContent>
  </complexType>

  <complexType name="Step">
    <sequence>
      <element name="parameter" type="tns:Parameter" minOccurs="0" maxOccurs="unbounded" />
      <element name="token" type="tns:Token" minOccurs="0" maxOccurs="unbounded" />
      <element name="step" type="tns:Step" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="name" type="string" use="required" />
    <attribute name="page" type="string" use="optional" />
    <attribute name="type" use="required">
      <simpleType>
        <restriction base="string">
          <enumeration value="CALL" />
          <enumeration value="CLICK" />
          <enumeration value="EXISTS" />
          <enumeration value="FUNCTION" />
          <enumeration value="GESTURE" />
          <enumeration value="RETURN" />
          <enumeration value="SET" />
          <enumeration value="VALUE" />
          <enumeration value="GET" />
          <enumeration value="WAIT" />
          <enumeration value="WAIT_FOR" />
          <enumeration value="ATTRIBUTE" />
          <enumeration value="LOOP" />
          <enumeration value="BREAK" />
          <enumeration value="DEVICE" />
          <enumeration value="FORK" />
          <enumeration value="VISIBLE" />
          <enumeration value="VERIFY_COLOR" />
          <enumeration value="VERIFY_CONTRAST" />
          <enumeration value="WINDOW" />
          <enumeration value="EXECJS" />
          <enumeration value="EXECWS" />
          <enumeration value="COMPARE" />
          <enumeration value="STRING" />
          <enumeration value="MATH" />
          <enumeration value="MOUSE" />
          <enumeration value="CACHE" />
          <enumeration value="REPORT" />
          <enumeration value="SYNC" />
          <enumeration value="OPEN_PAGE" />
          <enumeration value="ADD_COOKIE" />
          <enumeration value="DELETE_COOKIE" />
          <enumeration value="DELETE_COOKIES" />
          <enumeration value="GET_COOKIE" />
          <enumeration value="GET_COOKIES" />
          <enumeration value="ADD_DEVICE" />
          <enumeration value="AT" />
          <enumeration value="HAS_FOCUS" />
          <enumeration value="ALIGN" />
          <enumeration value="PERFECTO_SCRIPT" />
          <enumeration value="ELSE" />
          <enumeration value="STATE" />
          <enumeration value="ALERT" />
          <enumeration value="SQL" />
          <enumeration value="OPERATOR" />
          <enumeration value="NAVIGATE" />
          <enumeration value="VISUAL" />
          <enumeration value="SET_CONTENT_KEY" />
          <enumeration value="BROWSER" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="active" type="boolean" use="optional" default="true" />
    <attribute name="linkId" type="string" use="optional" />
    <attribute name="os" type="string" use="optional" />
    <attribute name="poi" type="string" use="optional" />
    <attribute name="threshold" type="integer" use="optional" default="0" />
    <attribute name="timed" type="boolean" use="optional" default="false" />
    <attribute name="inverse" type="boolean" use="optional" default="false" />
    <attribute name="startAt" type="boolean" use="optional" default="false" />
    <attribute name="breakpoint" type="boolean" use="optional" default="false" />
    <attribute name="wait" type="integer" use="optional" default="0" />
    <attribute name="failureMode" use="optional" default="ERROR">
      <simpleType>
        <restriction base="string">
          <enumeration value="ERROR" />
          <enumeration value="IGNORE" />
          <enumeration value="LOG_IGNORE" />
        </restriction>
      </simpleType>
    </attribute>

    <attribute name="validation" type="string" use="optional" />
    <attribute name="validationType" use="optional">
      <simpleType>
        <restriction base="string">
          <enumeration value="REGEX" />
          <enumeration value="EMPTY" />
          <enumeration value="NOT_EMPTY" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="context" type="string" use="optional" />
    <attribute name="device" type="string" use="optional" />
    <attribute name="tagNames" type="string" use="optional" />

  </complexType>

  <complexType name="Token">
    <attribute name="type" use="optional">
      <simpleType>
        <restriction base="string">
          <enumeration value="CONTEXT" />
          <enumeration value="PROPERTY" />
          <enumeration value="STATIC" />
          <enumeration value="CONTENT" />
          <enumeration value="DATA" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="value" type="string" use="required" />
    <attribute name="name" type="string" use="required" />
  </complexType>

  <complexType name="Parameter">
    <sequence>
      <element name="token" type="tns:Token" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="type" use="optional">
      <simpleType>
        <restriction base="string">
          <enumeration value="CONTEXT" />
          <enumeration value="PROPERTY" />
          <enumeration value="STATIC" />
          <enumeration value="CONTENT" />
          <enumeration value="DATA" />
          <enumeration value="FILE" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="value" type="string" use="required" />
    <attribute name="name" type="string" use="optional" />
    <attribute name="usage" type="string" use="optional" />
  </complexType>



</schema>

=== xframium/xframium-java/testing/tests/xTest/Flow Tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <test name="Flow Tests" tagNames="Keyword" timed="false" threshold="0" active="true" priority="1" severity="1">
    <description>Flow Tests</description>
    <step name="kw-flow" site="xTest" page="home" type="CALL2" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR" />
  </test>

  <test name="ERROR Test" tagNames="Keyword" timed="false" threshold="0" active="true" priority="1" severity="1">
    <description>Testing errors</description>
    <step name="error function" site="xTest" page="home" type="CALL2" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="IGNORE" />
    
    
    <step name="STRING" site="xTest" page="home" type="COMPARE2" active="true" threshold="1000" timed="false" inverse="false" wait="0" failureMode="IGNORE">
      <parameter type="STATIC" name="Value One" value="Test" />
      <parameter type="STATIC" name="Value Two" value="Test2" />
      <parameter type="STATIC" name="Operator" value="EQUALS" />
      <step name="STRING" site="xTest" page="home" type="COMPARE2" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR">
        <parameter type="STATIC" name="Value One" value="Test3" />
        <parameter type="STATIC" name="Value Two" value="Test4" />
        <parameter type="STATIC" name="Operator" value="EQUALS" />
      </step>
    </step>
    
    <step name="STRING" site="xTest" page="home" type="COMPARE2" active="true" threshold="0" timed="false" inverse="true " wait="0" failureMode="IGNORE">
      <parameter type="STATIC" name="Value One" value="Test" />
      <parameter type="STATIC" name="Value Two" value="Test2" />
      <parameter type="STATIC" name="Operator" value="EQUALS" />
      <step name="STRING" site="xTest" page="home" type="COMPARE2" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR">
        <parameter type="STATIC" name="Value One" value="Test3" />
        <parameter type="STATIC" name="Value Two" value="Test4" />
        <parameter type="STATIC" name="Operator" value="EQUALS" />
      </step>
    </step>
    
    <step name="STRING" site="xTest" page="home" type="COMPARE2" active="true" threshold="0" timed="false" inverse="true " wait="0" failureMode="IGNORE">
      <parameter type="STATIC" name="Value One" value="Test" />
      <parameter type="STATIC" name="Value Two" value="Test2" />
      <parameter type="STATIC" name="Operator" value="EQUALS" />
      <step name="STRING" site="xTest" page="home" type="COMPARE2" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="FAILURE">
        <parameter type="STATIC" name="Value One" value="Test3" />
        <parameter type="STATIC" name="Value Two" value="Test4" />
        <parameter type="STATIC" name="Operator" value="EQUALS" />
      </step>
    </step>
    
  </test>

  <test name="ERROR Test 2" tagNames="Keyword" timed="false" threshold="0" active="true" priority="1" severity="1">
    <step name="error function" site="xTest" page="home" type="CALL2" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="IGNORE" />
    <step name="failure function" site="xTest" page="home" type="CALL2" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="IGNORE" />
  </test>

  <function name="error function" active="true">
    <step name="STRING" site="xTest" page="home" type="COMPARE2" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR">
      <parameter type="STATIC" name="Value One" value="Test" />
      <parameter type="STATIC" name="Value Two" value="Test2" />
      <parameter type="STATIC" name="Operator" value="EQUALS" />
    </step>
  </function>
  
  <function name="failure function" active="true">
    <description>null</description>
    <step name="STRING" site="xTest" page="home" type="COMPARE2" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="FAILURE">
      <parameter type="STATIC" name="Value One" value="Test" />
      <parameter type="STATIC" name="Value Two" value="Test2" />
      <parameter type="STATIC" name="Operator" value="EQUALS" />
    </step>
  </function>
  

</suite>

=== xframium/xframium-java/testing/general/kw-window.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>

  <function name="kw-window" active="true">
    <!-- TITLE and URL -->
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="GET_TITLE" />
        <parameter type="STATIC" value="xFramium Testing" />
    </step>
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="GET_URL" />
        <parameter type="STATIC" value="http://xframium.org/testing.html" />
    </step>
    
    <!-- OPEN SECOND WINDOW -->
    <step type="CLICK" name="_testingTwo" page="home" />
    
    <!-- SWITCH, TITLE and URL -->
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="BY_WINTITLE" />
        <parameter type="STATIC" value="xFramium Second Page" />
    </step>
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="GET_TITLE" />
        <parameter type="STATIC" value="xFramium Second Page" />
    </step>
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="GET_URL" />
        <parameter type="STATIC" value="http://xframium.org/testing2.html" />
    </step>
    
    <!-- SWITCH BACK, TITLE and URL -->
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="BY_WINURL" />
        <parameter type="STATIC" value="http://xframium.org/testing.html" />
    </step>
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="GET_TITLE" />
        <parameter type="STATIC" value="xFramium Testing" />
    </step>
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="GET_URL" />
        <parameter type="STATIC" value="http://xframium.org/testing.html" />
    </step>
    <!-- SWITCH BACK, TITLE and URL -->
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="BY_WINURL" />
        <parameter type="STATIC" value="http://xframium.org/testing2.html" />
    </step>
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="GET_TITLE" />
        <parameter type="STATIC" value="xFramium Second Page" />
    </step>
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="GET_URL" />
        <parameter type="STATIC" value="http://xframium.org/testing2.html" />
    </step>
    
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="BY_WINURL" />
        <parameter type="STATIC" value="http://xframium.org/testing.html" />
    </step>
    <!--  SWITCH TO FRAME -->
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="BY_FRAME" />
        <parameter type="STATIC" value="frameName" />
    </step>
    <step type="EXISTS" name="screenTwo" page="page two" />

    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="BY_PARENTFRAME" />
    </step>
    <step type="EXISTS" name="screenTwo" page="page two" inverse="true" />
    
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="BY_ELEMENT" />
    </step>
    <step type="EXISTS" name="screenTwo" page="page two" />
    <step type="WINDOW" name="testingTwoFrame" page="home">
        <parameter type="STATIC" value="BY_PARENTFRAME" />
    </step>
    <step type="EXISTS" name="screenTwo" page="page two" inverse="true" />
    
  </function>

</suite>

=== xframium/xframium-java/testing/general/kw-align.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>

  <function name="kw-align" active="true">
    
    <step type="ALIGN" name="toggleButton" page="home" >
      <parameter type="STATIC" value="LEFT=toggleValue" />
    </step>
    
    <step type="ALIGN" name="confirmValue" page="home" >
      <parameter type="STATIC" value="RIGHT=promptValue" />
    </step>
    
    <step type="ALIGN" name="confirmValue" page="home" >
      <parameter type="STATIC" value="RIGHT=promptValue(50)" />
    </step>
    
    <step type="ALIGN" name="alertButton" page="home" >
      <parameter type="STATIC" value="TOP=confirmButton" />
      <parameter type="STATIC" value="BOTTOM=confirmButton" />
    </step>
    

  </function>

</suite>

=== xframium/xframium-java/testing/functions/xTest/kw-waitfor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    xFramium
   
    Copyright 2017 by Moreland Labs LTD (http://www.morelandlabs.com)
   
    Some open source application is free software: you can redistribute 
    it and/or modify it under the terms of the GNU General Public 
    License as published by the Free Software Foundation, either 
    version 3 of the License, or (at your option) any later version.
     
    Some open source application is distributed in the hope that it will 
    be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
     
    You should have received a copy of the GNU General Public License
    along with xFramium.  If not, see <http://www.gnu.org/licenses/>.
   
    @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>
 -->

<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
<function name="kw-waitfor" active="true">
<description>null</description>
<step name="aOpen" site="xTest" page="home" type="WAIT_FOR" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR"/>
<step name="aOpen" site="xTest" page="home" type="WAIT_FOR" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR">
<parameter type="STATIC" value="5"/>
</step>
<step name="deleteButton" site="xTest" page="home" type="EXISTS" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR"/>
<step name="deleteButton" site="xTest" page="home" type="VISIBLE" active="true" threshold="0" timed="false" inverse="true" wait="0" failureMode="ERROR"/>
<step name="aOpen.VISIBLE" site="xTest" page="home" type="WAIT_FOR" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR"/>
<step name="aOpen.CLICKABLE" site="xTest" page="home" type="WAIT_FOR" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR"/>
<step name="aOpen" site="xTest" page="home" type="CLICK" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR"/>
<step name="deleteButton.VISIBLE" site="xTest" page="home" type="WAIT_FOR" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR"/>
<step name="deleteButton.CLICKABLE" site="xTest" page="home" type="WAIT_FOR" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR"/>
<step name="deleteButton" site="xTest" page="home" type="VISIBLE" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR"/>
</function>
</suite>

=== xframium/xframium-java/testing/general/kw-compare.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>

  <function name="kw-compare" active="true">
    

    
    <step type="COMPARE" name="attributeCompare" page="home">
      <parameter type="DATA" value="callTest.value" />
      <parameter type="STATIC" value="one" />
    </step>
    
    <step type="COMPARE" name="attributeCompare" page="home">
      <parameter type="STATIC" value="one" />
      <parameter type="STATIC" value="one" />
    </step>
    
    <step type="COMPARE" name="attributeCompare" page="home" inverse="true">
      <parameter type="STATIC" value="two" />
      <parameter type="STATIC" value="one" />
    </step>
    

    

  </function>

</suite>

=== xframium/xframium-java/testing/general/kw-waitfor.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>

  <function name="kw-waitfor" active="true">
    
    <step type="WAIT_FOR" name="aOpen" page="home"  />
    <step type="WAIT_FOR" name="aOpen" page="home"  >
      <parameter type="STATIC" value="5" />
    </step>
    <step type="EXISTS" name="deleteButton" page="home"  />
    
    <step type="VISIBLE" name="deleteButton" page="home" inverse="true" />
    <step type="WAIT_FOR" name="aOpen.VISIBLE" page="home" />
    <step type="WAIT_FOR" name="aOpen.CLICKABLE" page="home" />
    <step type="CLICK" name="aOpen" page="home" />
    <step type="WAIT_FOR" name="deleteButton.VISIBLE" page="home" />
    <step type="WAIT_FOR" name="deleteButton.CLICKABLE" page="home" />
    <step type="VISIBLE" name="deleteButton" page="home" />


  </function>

</suite>

=== xframium/xframium-java/testing/functions/xTest/kw-execws.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
<function name="kw-execws" active="true">
<description></description>
<step name="SOAP Call" site="xTest" page="Home" type="EXECWS" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR" context="soap">
<parameter type="STATIC" name="url" value="http://www.webservicex.net/FinanceService.asmx"/>
<parameter type="STATIC" name="method" value="POST"/>
<parameter type="STATIC" name="media-type" value="text/xml"/>
<parameter type="STATIC" name="type" value="SOAP"/>
<parameter type="FILE" name="payload"><token type="STATIC" name="loanAmount" value="100000"/>
<token type="STATIC" name="extraCost" value="0"/>
<token type="STATIC" name="interestRate" value="5"/>
<token type="STATIC" name="months" value="360"/>
</parameter>
<parameter type="STATIC" name="type" value="xml" usage="OUTPUT"/>
<parameter type="STATIC" name="var1" value="//APRResult" usage="OUTPUT"/>
<parameter type="STATIC" name="var2" value="//APRResult" usage="OUTPUT"/>
<parameter type="STATIC" name="var3" value="//APRResult" usage="OUTPUT"/>
</step>
<step name="compare" site="xTest" page="home" type="REPORT" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR">
<parameter type="CONTEXT" value="soap_var1"/>
<parameter type="CONTEXT" value="soap_var2"/>
<parameter type="CONTEXT" value="soap_var3"/>
</step>
<step name="compare" site="xTest" page="home" type="COMPARE" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR">
<parameter type="STATIC" value="536.82162301213975"/>
<parameter type="CONTEXT" value="soap_var1"/>
</step>
<step name="REST Call" site="xTest" page="Home" type="EXECWS" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR" context="rest">
<parameter type="STATIC" name="url" value="http://www.webservicex.net/FinanceService.asmx/APR?LoanAmount={loanAmount}&amp;ExtraCost={extraCost}&amp;InterestRate={interestRate}&amp;Months={months}"><token type="STATIC" name="loanAmount" value="100000"/>
<token type="STATIC" name="extraCost" value="15000"/>
<token type="STATIC" name="interestRate" value="5"/>
<token type="STATIC" name="months" value="360"/>
</parameter>
<parameter type="STATIC" name="method" value="GET"/>
<parameter type="STATIC" name="media-type" value="text/xml"/>
<parameter type="STATIC" name="type" value="REST"/>
<parameter type="STATIC" name="type" value="xml" usage="OUTPUT"/>
<parameter type="STATIC" name="var1" value="//double" usage="OUTPUT"/>
</step>
<step name="compare" site="xTest" page="home" type="COMPARE" active="true" threshold="0" timed="false" inverse="false" wait="0" failureMode="ERROR">
<parameter type="STATIC" value="617.34486646396078"/>
<parameter type="CONTEXT" value="rest_var1"/>
</step>
</function>
</suite>

=== xframium/xframium-java/testing/general/kw-checkcolor.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.xframium.org/testRegistry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xframium.org/testRegistry http://www.xframium.org/xsd/pageManagement/testRegistry.xsd">
  <model>
    
    <page name="home" />

  </model>

  <function name="kw-checkcolor" active="true">

    <step type="VERIFY_COLOR" name="alertButton" page="home">
      <parameter type="STATIC" value="high" />
      <parameter type="STATIC" value="5,5" />
    </step>
    
    <step type="VERIFY_COLOR" name="colorCheck" page="home" >
      <parameter type="STATIC" value="high" />
      <parameter type="STATIC" value="5,5" />
      <parameter type="STATIC" value="#337ab7" />
      <parameter type="STATIC" value="0" />
    </step>
    
    <step type="VERIFY_COLOR" name="colorCheck" page="home" context="alertColor">
      <parameter type="STATIC" value="high" />
      <parameter type="STATIC" value="5,5" />
    </step>

    <step type="COMPARE" name="checkColor" page="home">
      <parameter type="CONTEXT" value="alertColor" />
      <parameter type="STATIC" value="-13403465" />
    </step>
    
    <step type="VERIFY_COLOR" name="colorCheck" page="home" >
      <parameter type="STATIC" value="high" />
      <parameter type="STATIC" value="5,5" />
      <parameter type="STATIC" value="51,122,183" />
      <parameter type="STATIC" value="5" />
    </step>
    
    <step type="VERIFY_COLOR" name="colorCheck" page="home" >
      <parameter type="STATIC" value="high" />
      <parameter type="STATIC" value="5,5" />
      <parameter type="STATIC" value="-13403465" />
      <parameter type="STATIC" value="5" />
    </step>
    
    <step type="VERIFY_COLOR" name="colorCheck" page="home" inverse="true" >
      <parameter type="STATIC" value="high" />
      <parameter type="STATIC" value="5,5" />
      <parameter type="STATIC" value="#000000" />
      <parameter type="STATIC" value="0" />
    </step>
    


  </function>

</suite>
